import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { FloatLabelModule } from 'primeng/floatlabel';
import { DatePickerModule } from 'primeng/datepicker';
import { TagModule } from 'primeng/tag';
import { ToastModule } from 'primeng/toast';
import { TextareaModule } from 'primeng/textarea';
import { CheckboxModule } from 'primeng/checkbox';
import { MessageService } from 'primeng/api';
import { AccountsService } from '../../services/accounts/accounts';

@Component({
  selector: 'app-journal-entries',
  standalone: true,
  imports: [CommonModule, FormsModule, TableModule, ButtonModule, DialogModule,
    InputTextModule, SelectModule, FloatLabelModule, DatePickerModule,
    TagModule, ToastModule, TextareaModule, CheckboxModule],
  providers: [MessageService],
  templateUrl: './journal-entries.html',
  styleUrl: './journal-entries.css'
})
export class JournalEntries implements OnInit {
  entries: any[] = [];
  total = 0;
  loading = false;
  showDialog = false;
  showDetail = false;
  selectedEntry: any = null;
  page = 1;

  filters: any = { fromDate: null, toDate: null, isAutoGenerated: '' };
  form: any = { entryDate: null, narration: '', lines: [] };
  accounts: any[] = [];

  autoGenOptions = [
    { label: 'All', value: '' },
    { label: 'Manual', value: 'false' },
    { label: 'Auto-Generated', value: 'true' },
  ];

  constructor(private svc: AccountsService, private msg: MessageService) {}

  ngOnInit() {
    this.load();
    this.svc.getAccountsDropdown().subscribe({ next: d => this.accounts = d });
  }

  load() {
    this.loading = true;
    const f: any = { page: this.page, limit: 20 };
    if (this.filters.isAutoGenerated !== '') f.isAutoGenerated = this.filters.isAutoGenerated;
    if (this.filters.fromDate) f.fromDate = this.filters.fromDate.toISOString();
    if (this.filters.toDate) f.toDate = this.filters.toDate.toISOString();
    this.svc.getJournalEntries(f).subscribe({
      next: d => { this.entries = d.data; this.total = d.total; this.loading = false; },
      error: () => this.loading = false
    });
  }

  openNew() {
    this.form = { entryDate: new Date(), narration: '', lines: [
      { debitAccountId: null, creditAccountId: null, amount: null, narration: '' },
      { debitAccountId: null, creditAccountId: null, amount: null, narration: '' },
    ]};
    this.showDialog = true;
  }

  addLine() {
    this.form.lines.push({ debitAccountId: null, creditAccountId: null, amount: null, narration: '' });
  }

  removeLine(i: number) {
    if (this.form.lines.length > 2) this.form.lines.splice(i, 1);
  }

  get totalDebit(): number { return this.form.lines.reduce((s: number, l: any) => l.debitAccountId ? s + (Number(l.amount) || 0) : s, 0); }
  get totalCredit(): number { return this.form.lines.reduce((s: number, l: any) => l.creditAccountId ? s + (Number(l.amount) || 0) : s, 0); }
  get isBalanced(): boolean { return Math.abs(this.totalDebit - this.totalCredit) < 0.01; }

  save() {
    if (!this.isBalanced) {
      this.msg.add({ severity: 'warn', summary: 'Not Balanced', detail: 'Total debits must equal total credits' }); return;
    }
    this.svc.createJournalEntry(this.form).subscribe({
      next: () => { this.msg.add({ severity: 'success', summary: 'Entry Created' }); this.showDialog = false; this.load(); },
      error: (e) => this.msg.add({ severity: 'error', summary: 'Error', detail: e?.error?.message || 'Failed' })
    });
  }

  viewDetail(row: any) {
    this.svc.getJournalEntryById(row.id).subscribe({ next: d => { this.selectedEntry = d; this.showDetail = true; } });
  }
}
